name: Python CI with Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      run: echo "Checked out the code"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'
      run: echo "Python 3.12.7 is set up"

    - name: Install dependencies
      run: |
        echo "Upgrading pip"
        python -m pip install --upgrade pip
        echo "Installing dependencies from requirements.txt"
        pip install -r requirements.txt

    - name: Add mock HTML files
      run: |
        mkdir -p mock_data
        echo '<html><body
